package Vista;

/* Importación de librerias/dependencias */
import javax.swing.*;
import Controladores.AdministradorArchivos;
import Controladores.Analizador;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.*;

/**
 *
 * @author THOMAS CAMILO VANEGAS ACEVEDO; ID:000287437
 * 
 */

public class AntivirusAppHome extends javax.swing.JFrame {
    
    private File archivo;
    private byte[] bytesArchivo;
    
    public AntivirusAppHome() {
        
        /* Ejecutando el método initComponents */
        initComponents();

        // Método que permite que el JFrame se inicie en el centro de la pantalla
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitleDetectorVirus = new javax.swing.JLabel();
        LblSeleccionarArchivoAnalizar = new javax.swing.JLabel();
        InputArchivo = new javax.swing.JTextField();
        BtnAnalizarArchivo = new javax.swing.JButton();
        LblContenidoArchivoBytes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaContenidoBytes = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnBucarArchivo = new javax.swing.JButton();
        BtnMostrarAutomata = new javax.swing.JButton();
        Separator1 = new javax.swing.JSeparator();
        Separator2 = new javax.swing.JSeparator();
        Separator3 = new javax.swing.JSeparator();
        Separator4 = new javax.swing.JSeparator();
        BtnSalirApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitleDetectorVirus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblTitleDetectorVirus.setText("Detector de Virus");

        LblSeleccionarArchivoAnalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblSeleccionarArchivoAnalizar.setText("Seleccione el Archivo a Analizar");

        InputArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputArchivoActionPerformed(evt);
            }
        });

        BtnAnalizarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnAnalizarArchivo.setText("ANALIZAR ARCHIVO");
        BtnAnalizarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnalizarArchivoActionPerformed(evt);
            }
        });

        LblContenidoArchivoBytes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblContenidoArchivoBytes.setText("Contenido de su Archivo en Bytes");

        TextAreaContenidoBytes.setColumns(20);
        TextAreaContenidoBytes.setRows(5);
        jScrollPane1.setViewportView(TextAreaContenidoBytes);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del Archivo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Estado del Autómata Finito");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Resultado del Análisis");

        BtnBucarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnBucarArchivo.setText("Buscar Archivo a Analizar");
        BtnBucarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBucarArchivoActionPerformed(evt);
            }
        });

        BtnMostrarAutomata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnMostrarAutomata.setText("Mostrar Diseño Automata");
        BtnMostrarAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarAutomataActionPerformed(evt);
            }
        });

        Separator1.setBackground(new java.awt.Color(0, 0, 0));
        Separator1.setForeground(new java.awt.Color(0, 0, 0));

        Separator2.setBackground(new java.awt.Color(0, 0, 0));
        Separator2.setForeground(new java.awt.Color(0, 0, 0));

        Separator3.setBackground(new java.awt.Color(0, 0, 0));
        Separator3.setForeground(new java.awt.Color(0, 0, 0));

        Separator4.setBackground(new java.awt.Color(0, 0, 0));
        Separator4.setForeground(new java.awt.Color(0, 0, 0));

        BtnSalirApp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSalirApp.setForeground(new java.awt.Color(255, 0, 0));
        BtnSalirApp.setText("SALIR DE LA APP");
        BtnSalirApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator1)
            .addComponent(Separator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(LblTitleDetectorVirus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(BtnMostrarAutomata))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(BtnSalirApp)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Separator4))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(InputArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnBucarArchivo))
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblSeleccionarArchivoAnalizar)
                                .addGap(180, 180, 180))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblContenidoArchivoBytes)
                                .addGap(174, 174, 174))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(208, 208, 208))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnAnalizarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitleDetectorVirus)
                .addGap(12, 12, 12)
                .addComponent(LblSeleccionarArchivoAnalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBucarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblContenidoArchivoBytes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(BtnAnalizarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnMostrarAutomata)
                .addGap(18, 18, 18)
                .addComponent(Separator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSalirApp)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputArchivoActionPerformed

    
    
    
    
    
    // BOTÓN ANALIZAR ARCHIVO
    private void BtnAnalizarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnalizarArchivoActionPerformed
        
        Analizador analizador = new Analizador(bytesArchivo);
        
        
        
    }//GEN-LAST:event_BtnAnalizarArchivoActionPerformed

    
    
    
    
    
    private void BtnBucarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBucarArchivoActionPerformed

        // Instanciando la Clase JFileChooser;
        JFileChooser exploradorArchivos = new JFileChooser();
        
        String cadenaBytesArchivo = "";
        
        // Invocando el método showOpenDialog para abrir el buscador de archivos.
        exploradorArchivos.showOpenDialog(this);
        // Obteniedo la ruta para insertarse en el InputFile
        InputArchivo.setText(exploradorArchivos.getSelectedFile().toPath().toString());
        
        try {
            AdministradorArchivos administrador = new AdministradorArchivos(exploradorArchivos.getSelectedFile());
            
            bytesArchivo = administrador.getBytesArchivo();
            
            // Se recorre el array bytesArchivo para insertarlo en una cadena.
            for (int i = 0; i < bytesArchivo.length; i++) {
                
                cadenaBytesArchivo = cadenaBytesArchivo + bytesArchivo[i] + " ";
            
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(AntivirusAppHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TextAreaContenidoBytes.setText(cadenaBytesArchivo);
        
        
    }//GEN-LAST:event_BtnBucarArchivoActionPerformed

    private void BtnMostrarAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarAutomataActionPerformed
        
        MostrarDisenoAutomata disenoAutomata = new MostrarDisenoAutomata();
        disenoAutomata.setVisible(true);
        
    }//GEN-LAST:event_BtnMostrarAutomataActionPerformed

    private void BtnSalirAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalirAppActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AntivirusAppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AntivirusAppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AntivirusAppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AntivirusAppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AntivirusAppHome().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnalizarArchivo;
    private javax.swing.JButton BtnBucarArchivo;
    private javax.swing.JButton BtnMostrarAutomata;
    private javax.swing.JButton BtnSalirApp;
    private javax.swing.JTextField InputArchivo;
    private javax.swing.JLabel LblContenidoArchivoBytes;
    private javax.swing.JLabel LblSeleccionarArchivoAnalizar;
    private javax.swing.JLabel LblTitleDetectorVirus;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSeparator Separator4;
    private javax.swing.JTextArea TextAreaContenidoBytes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
